### ISSUE TITLE
train test split issue

### ISSUE THREAD

**Issue by notes-ml** [waylandy/kibby#1]
Hi thank you for this great work! I would like to use your training and test splits. In the paper you mention that you used 35,000 examples, do you have the indices that correspond to the test split if I read your `conservation_scores.csv` file?

Again, thank you.

**Comment by waylandy** [comment]
Hey thanks! We tried multiple test/train splits, but I think this one should be the final one. We only trained with Pfam "Domains", while Pfam "Families" were purely used for testing.

[training.zip](https://github.com/waylandy/kibby/files/10686765/training.zip)

Interested in hearing your results!

**Comment by notes-ml** [comment]
Thank you! this is really helpful for testing and benchmarking other pLM, e.g. [Ankh](https://github.com/agemagician/Ankh), I will try to share my findings.

**Comment by waylandy** [comment]
sounds awesome! 
definitely interested in seeing how it performs with Ankh
